AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'Rakefile'
    - 'node_modules/**/*'
    # Enable app directory checking for better code quality

# Inherit from todo list while we're fixing issues
inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'db/seeds.rb'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'db/seeds.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/seeds.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
